config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  devise_for :users
  
  namespace :admin do
    root "users#index"

    resources :users, only: [:index, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  root "articles#index"
  resources :categories, only: [:show]
  resources :articles do
    member do
      post :comment
      post :collect
      post :uncollect
    end
  end
  resources :users do
    member do
      get :draft
      get :collection
      get :follower
      get :comment
    end
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :feeds, only: [:index]
  resources :invitations, only: [:create, :destroy] do
    member do
      post :accept
      post :decline
    end
  end

  resources :friendships, only: [:destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :auth
  validates_presence_of :state
  mount_uploader :image, ImageUploader
  paginates_per 20
  belongs_to :user
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories, source: :category, dependent: :destroy
  has_many :comments
  has_many :collections
  has_many :collection_users, through: :collections, source: :user, dependent: :destroy
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApiController
  before_action :authenticate_user!, except: :index
  def index
    @articles = Article.all
    render json: {
        data: @articles
      } 
  end

  def show
    @article = Article.find_by(id: params[:id])
    unless @article
      render json: {
        message: "Can't find the article!",
        status: 400
      }
    else
      render json: @article
    end
  end

  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.build(article_params)
    if @article.save
      category_ids = params[:category_ids].split(',')
      category_ids.each do |category_id|
        @article.categories << Category.find(category_id)
      end
      render json: {
        message: "成功建立文章",
        result: @article
      }
    else
      render json: {
        errors: @article.errors
      }
    end
  end

  def update
    @article = Article.find_by(id: params[:id])
    if @article.update(article_params)
      render json: {
        message: "成功更新文章",
        result: @article
      }
    else
      render json: {
        errors: article.errors
      }
    end
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy
    render json: {
      message: "成功刪除文章"
    }
  end

  private

  def article_params
    params.permit(:title, :content, :auth, :category_ids, :state, :image, :user_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  def index
    @order_tag = params[:tag]
    @category_tag = "全部"
    case params[:tag]
    when nil then @articles =  viewable_articles.order(:id).page(params[:page])
    when 'last_replied_at' then @articles =  viewable_articles.order('last_replied_at DESC').page(params[:page])
    when 'comments_count' then @articles =  viewable_articles.order(comments_count: :desc).page(params[:page])
    when 'views_count' then @articles =  viewable_articles.order(views_count: :desc).page(params[:page])
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      params[:article][:category_ids].delete("")
      params[:article][:category_ids].each do |category_id|
        @article.categories << Category.find(category_id)
      end
      flash[:notice] = "成功新增文章"
      redirect_to @article
    else
      flash[:alert] = "新增文章失敗"
      render :new
    end
  end

  def show
    if helpers.article_can_show?(@article)
      @article.views_count += 1
      @article.save
      @user = @article.user
      @comment = Comment.new
      @comments = @article.comments.order(created_at: :desc).page(params[:page]).per(5)
    else
      flash[:alert] = "無權限觀看"
      redirect_to root_path
    end
  end

  def edit
    unless @article.user == current_user
      flash[:alert] = "作者才可操作"
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    if @article.update_attributes(article_params)
      @article.categories.delete_all
      params[:article][:category_ids].delete("")
      params[:article][:category_ids].each do |category_id|
        @article.categories << Category.find(category_id)
      end
      flash[:notice] = "成功修改文章"
      redirect_to @article
    else
      flash[:alert] = "新增文章失敗"
      render :new
    end
  end

  def destroy
    if current_user == @article.user || current_user.role == 'admin'
      @article.delete
      flash[:notice] = "成功刪除"
      redirect_to current_user
    else
      flash[:alert] = "無法操作"
      redirect_back(fallback_location: root_path)
    end
  end

  def comment
    # binding.pry
    article = Article.find(params[:id])
    comment = article.comments.build(comment_params)
    comment.update(user_id: current_user.id)
    if comment.save
      article.last_replied_at = Time.zone.now
      article.save
      flash[:notice] = "成功新增留言"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "新增留言失敗"
      redirect_back(fallback_location: root_path)
    end
  end

  def collect
    @article = Article.find(params[:id])
    @article.collections.create(user_id: current_user.id)
    # flash.now[:notice]= "成功收藏此文章"
    # redirect_back(fallback_location: root_path)
  end

  def uncollect
    @article = Article.find(params[:id])
    collection = Collection.where(user_id: current_user.id, article_id: params[:id])[0]
    collection.delete
    # flash[:notice] = "成功取消收藏"
    # redirect_back(fallback_location: root_path)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :auth, :category_ids, :state, :image)
  end

  def comment_params
    params.require(:comment).permit(:content, :article_id)
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def viewable_articles
    Article.where(state: 'publish')
  end
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def last_replied_at(article)
    if article.last_replied_at
      article.last_replied_at.strftime("%m/%d/%Y")
    end
  end

  def user_collected?(article)
    # binding.pry
    current_user.collection_articles.include?(article)
  end

  def author?(article)
    article.user == current_user
  end

  def article_can_show?(article)
    if author?(article) || article.auth == 'all'
      true
    elsif article.auth == 'self'
      false
    else
      is_friend?(article.user)
    end

  end

  def transcript_tag(tag)
    case tag
    when nil then '文章編號'
    when 'last_replied_at' then '最後回覆時間'
    when 'comments_count' then '回覆數'
    when 'views_count' then '觀看數'
    end
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
  <%= f.input :title, label: "主題", class: "form-control" %>
  <%= f.input :content, label: "內容", as: :text, :input_html => { :rows => 20 }, class: "form-control"%>
  <%= f.input :auth, label: '誰可以看到', as: :radio_buttons, collection: [['全部', 'all'], ['朋友', 'friends'], ['我自己', 'self']], class: "form-control" %>
  <%= f.association :categories, label: '分類', as: :check_boxes, class: "form-control" %>
  <%= f.input :state, label: "發佈狀態", collection: [["草稿", 'draft'], ['發佈','publish']], selected:["publish"], class: "form-control" %>
  <%= f.file_field :image %>
  <br>
  <br>
  <%= f.button :submit, '提交', class: "btn btn-primary" %>
<% end %>

app/views/articles/collect.js.erb
<% html = j( render "shared/collection", article: @article ) %>
$('#collect-<%= @article.id %>').html("<%= html %>")

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="dropdown margin-top-bottom">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    排序方式
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to "最後回覆時間", articles_path(tag: 'last_replied_at'), class: 'dropdown-item' %>
    <%= link_to "回覆數", articles_path(tag: 'comments_count'), class: 'dropdown-item' %>
    <%= link_to "觀看數", articles_path(tag: 'views_count'), class: 'dropdown-item' %>
  </div>
</div>
<table class="table">
  <thead>
    <th scope="col">回覆數</th>
    <th scope="col">標題</th>
    <th scope="col">內容</th> 
    <th scope="col">最後回覆時間</th>
    <th scope="col">觀看次數</th>
    <th scope="col">作者</th>
  </thead>
  <tbody>
    <!-- 在前端擋住不能show的文章 -->
    <% @articles.each do |article| %>
      <% if article_can_show?(article) %>
        <tr>
          <td><%= article.comments_count %></td>
          <td>
            <%= link_to article.title, article %>
          </td>
          <td><%= truncate article.content %></td>
          <td><%= last_replied_at(article) %></td>
          <td><i class="fa fa-eye fa-lg"> </i> <%= article.views_count %></td>
          <td><%= link_to article.user.name, article.user %></td>
        </tr> 
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>Add new article</h1>
<%= simple_form_for @article do |f| %>
  <%= f.input :title, label: "主題" %>
  <%= f.input :content, label: "內容", as: :text%>
  <%= f.input :auth, label: '誰可以看到', as: :radio_buttons, collection: [['全部', 'all'], ['朋友', 'friends'], ['我自己', 'self']] %>
  <%= f.association :categories, label: '分類', as: :check_boxes %>
  <%= f.button :submit, '提交', class: "btn btn-primary" %>
<% end %>

app/views/articles/show.html.erb
<%= render "shared/user_profile", user: @user %>
<div class="row">
  <div class="col-md-12 text-center">
    <h2><%= @article.title %></h2>  
  </div>
  <div class="col-md-12">
    <div class="text-center">
      <%= image_tag @article.image_url if @article.image_url %>
    </div>
    <p><%= @article.content %></p>
    <p class="sm-grey">
      Categories:
      <% @article.categories.each do |category| %>
        #<%= category.name %>
      <% end %>
    </p>
  </div>
  <div class="col-md-12 text-right margin-top-bottom">
    <%= render 'shared/admin_delete_button', article: @article %>
    <%= render 'shared/author_panel', article: @article %>
    <%= render "shared/collection", article: @article %>
    <hr>
  </div>
  <div class="col-md-12">
    <%= simple_form_for @comment, url: comment_article_path, method: :post do |f| %>
      <%= f.input :content, label: "留下評論" %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
  <% unless @comments.blank? %>
    <div class="col-md-12">
      <% @comments.each do |comment| %>
        <div class="row comment-panel" id="comment-<%= comment.id %>">
          <%= render 'shared/comment_table', comment: comment %>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>
</div>
<div class="padding-top">
  <%= paginate @comments %>
</div>

app/views/articles/uncollect.js.erb
<% html = j( render "shared/collection", article: @article ) %>
$('#collect-<%= @article.id %>').html("<%= html %>")