config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  devise_for :users
  
  namespace :admin do
    root "users#index"

    resources :users, only: [:index, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  root "articles#index"
  resources :categories, only: [:show]
  resources :articles do
    member do
      post :comment
      post :collect
      post :uncollect
    end
  end
  resources :users do
    member do
      get :draft
      get :collection
      get :follower
      get :comment
    end
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :feeds, only: [:index]
  resources :invitations, only: [:create, :destroy] do
    member do
      post :accept
      post :decline
    end
  end

  resources :friendships, only: [:destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commentted_articles, through: :comments, source: :article
  has_many :collections, dependent: :destroy
  has_many :collection_articles, through: :collections, source: :article

  has_many :invitations, -> {where(state: 'pending')}, foreign_key: :inviter_id, dependent: :destroy
  has_many :invitees, through: :invitations

  has_many :reverse_invitations, -> {where(state: 'pending')}, foreign_key: :invitee_id, class_name: "Invitation", dependent: :destroy
  has_many :inviters, through: :reverse_invitations

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  before_create :generate_authentication_token

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

  def is_friend_of?(user)
    self.friends.include?(user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_back(fallback_location: root_path)
  end

  private

  def user_params
    params.require(:user).permit(:role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.where(state: 'publish')
  end

  def draft
    @user = User.find(params[:id])
    if @user == current_user
      @drafts = @user.articles.where(state: 'draft')
    else
      flash[:alert] = "禁止訪問"
      redirect_back(fallback_location: root_path)
    end
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "個人資料更新成功"
      redirect_to @user
    else
      flash[:alert] = "無法操作"
      render :edit
    end
  end

  def comment
    @user = User.find(params[:id])
    # binding.pry
    @articles = @user.commentted_articles.uniq
  end

  def collection
    @user = User.find(params[:id])
    @articles = @user.collection_articles
  end

  def follower
    @user = User.find(params[:id])
    @inviters = @user.inviters
    @invitees = @user.invitees
    @friends = @user.friends
  end

  private

  def user_params
    params.require(:user).permit(:name, :description)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, class_value = '')
    image_tag(gravatar_url(user), alt: user.email, class: class_value)
  end

  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end

  def title(user)
    user == current_user ? "我" : user.name
  end

  def admin?
    current_user.role == 'admin'
  end
end

app/views/users/collection.html.erb
<%= render "shared/user_profile", user: @user %>
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <%= link_to "#{title(@user)}的文章", @user, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{title(@user)}回覆過的文章", comment_user_path(@user), class: "nav-link" %>
  </li>
  <% if @user == current_user %>
    <li class="nav-item">
      <%= link_to "#{title(@user)}的收藏", collection_user_path, class: "nav-link active" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的草稿", draft_user_path(@user), class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的朋友", follower_user_path(@user), class: "nav-link" %>
    </li>
  <% end %>
</ul>

<%= render "shared/articles_list", articles: @articles %>

app/views/users/comment.html.erb
<%= render "shared/user_profile", user: @user %>
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <%= link_to "#{title(@user)}的文章", @user, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{title(@user)}回覆過的文章", comment_user_path(@user), class: "nav-link active" %>
  </li>
  <% if @user == current_user %>
    <li class="nav-item">
      <%= link_to "#{title(@user)}的收藏", collection_user_path, class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的草稿", draft_user_path(@user), class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的朋友", follower_user_path(@user), class: "nav-link" %>
    </li>
  <% end %>
</ul>
<%= render "shared/articles_list", articles: @articles %>

app/views/users/draft.html.erb
<%= render "shared/user_profile", user: @user %>
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <%= link_to "#{title(@user)}的文章", @user, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{title(@user)}回覆過的文章", comment_user_path(@user), class: "nav-link" %>
  </li>
  <% if @user == current_user %>
    <li class="nav-item">
      <%= link_to "#{title(@user)}的收藏", collection_user_path, class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的草稿", draft_user_path(@user), class: "nav-link active" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的朋友", follower_user_path(@user), class: "nav-link" %>
    </li>
  <% end %>
</ul>
<%= render "shared/articles_list", articles: @drafts %>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: "名字" %>
  <%= f.input :description, label: "自我介紹" %>
  <%= f.button :submit, '送出', class: "btn btn-primary" %>
<% end %>

app/views/users/follower.html.erb
<%= render "shared/user_profile", user: @user %>
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <%= link_to "#{title(@user)}的文章", @user, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{title(@user)}回覆過的文章", comment_user_path(@user), class: "nav-link" %>
  </li>
  <% if @user == current_user %>
    <li class="nav-item">
      <%= link_to "#{title(@user)}的收藏", collection_user_path, class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的草稿", draft_user_path(@user), class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的朋友", follower_user_path(@user), class: "nav-link active" %>
    </li>
  <% end %>
</ul>

<div class="row padding-top-user">
  <% if current_user == @user %>
    <div class="col-md-12 text-center follower-column">
      <h2>發出的好友邀請</h2>
      <div class="row">
        <% @invitees.each do |invitee| %>
          <div class="col-md-2">
            <%= link_to invitee do %>
              <%= gravatar_for(invitee, 'padding-bottom-avatar') %>
              <p><%= invitee.name %></p> 
              <% unless invitee == current_user %>
                <%= render "shared/friend_button", user: invitee %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-12 text-center follower-column">
      <h2>邀請好友請求</h2>
      <div class="row">
        <% @inviters.each do |inviter| %>
          <div class="col-md-2">
            <%= link_to inviter do %>
              <%= gravatar_for(inviter, 'padding-bottom-avatar') %>
              <% unless inviter == current_user %>
                <%= render "shared/friend_button", user: inviter %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  
  <div class="col-md-12 text-center follower-column">
    <h2>好友列表</h2>
    <div class="row">
      <% @friends.each do |friend| %>
        <div class="col-md-2">
          <%= link_to friend do %>
            <%= gravatar_for(friend, 'padding-bottom-avatar') %>
            <% unless friend == current_user %>
              <%= render "shared/friend_button", user: friend %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/user_profile", user: @user %>
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <%= link_to "#{title(@user)}的文章", @user, class: "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{title(@user)}回覆過的文章", comment_user_path(@user), class: "nav-link" %>
  </li>
  <% if @user == current_user %>
    <li class="nav-item">
      <%= link_to "#{title(@user)}的收藏", collection_user_path, class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的草稿", draft_user_path(@user), class: "nav-link" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "#{title(@user)}的朋友", follower_user_path(@user), class: "nav-link" %>
    </li>
  <% end %>
</ul>
<%= render "shared/articles_list", articles: @articles %>
<%= link_to "新增文章", new_article_path, class: "btn btn-primary" %>