config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  devise_for :users
  
  namespace :admin do
    root "users#index"

    resources :users, only: [:index, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  root "articles#index"
  resources :categories, only: [:show]
  resources :articles do
    member do
      post :comment
      post :collect
      post :uncollect
    end
  end
  resources :users do
    member do
      get :draft
      get :collection
      get :follower
      get :comment
    end
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :feeds, only: [:index]
  resources :invitations, only: [:create, :destroy] do
    member do
      post :accept
      post :decline
    end
  end

  resources :friendships, only: [:destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, message: "分類名字不能為空"
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @category = Category.new
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      # flash[:notice] = "修改成功"
      # redirect_to admin_categories_path
    else
      flash[:alert] = "修改失敗"
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      # flash[:notice] = "新增類別成功"
      # redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "新增失敗"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.articles.blank?
      @category.delete
      # redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "無法刪除有文章使用的分類"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @order_tag = params[:tag]
    @category = Category.find(params[:id])
    @category_tag = @category.name
    case params[:tag]
    when nil then @articles =  viewable_articles(@category).order(:id).page(params[:page])
    when 'last_replied_at' then @articles =  viewable_articles(@category).order('last_replied_at DESC').page(params[:page])
    when 'comments_count' then @articles =  viewable_articles(@category).order(comments_count: :desc).page(params[:page])
    when 'views_count' then @articles =  viewable_articles(@category).order(views_count: :desc).page(params[:page])
    end
  end

  private

  def viewable_articles(category)
    @category.articles.where(state: 'publish')
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category_row.html.erb
<td class="text-center" id="category-<%= category.id %>"><%= category.name %></td>
<td class="text-center">
  <%= link_to edit_admin_category_path(category), remote: true do %>
    <%= fa_icon "pencil", class: "fa-2x icon-space" %>
  <% end %>
  <%= link_to admin_category_path(category), method: :delete, remote: true do %>
    <%= fa_icon "trash", class: "fa-2x icon-space"%>
  <% end %>
</td>

app/views/admin/categories/_form.html.erb
<%= simple_form_for [:admin, category], remote: true do |f| %>
  <%= f.input :name, label: false %>
  <%= f.button :submit, '送出', class: 'btn btn-primary' %>
<% end %>

app/views/admin/categories/create.js.erb
var category = document.createElement("tr");

category.id = "row-<%= @category.id %>";

category.innerHTML = "<%= j( render 'category_row', category: @category ) %>";
$("#tbody").append(category);
$('#category_name').val("");

app/views/admin/categories/destroy.js.erb
$('#row-<%= @category.id %>').remove();

app/views/admin/categories/edit.html.erb
<%= render "form", category: @category %>

app/views/admin/categories/edit.js.erb
<% html = j( render "form", category: @category ) %>
$('#category-<%= @category.id %>').html("<%= html %>")

app/views/admin/categories/index.html.erb
<div class="padding-top">
  <ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <%= link_to "新增編輯分類", admin_categories_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "更改使用者權限", admin_users_path, class: "nav-link" %>
    </li>
  </ul>
</div>

<div class="row padding-top">
  <div class="col-md-6">
    <%= render "form", category: @category %>
  </div>  
</div>  

<div class="row padding-top">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <th scope="col" class="text-center">Name</th>
        <th scope="col"></th>
      </thead>
      <tbody id="tbody">
        <% @categories.each do |category| %>
        <tr id="row-<%= category.id %>" >
          <%= render 'category_row', category: category %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/categories/update.js.erb
$('#category-<%= @category.id %>').html("<%= @category.name %>")