config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  devise_for :users
  
  namespace :admin do
    root "users#index"

    resources :users, only: [:index, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  root "articles#index"
  resources :categories, only: [:show]
  resources :articles do
    member do
      post :comment
      post :collect
      post :uncollect
    end
  end
  resources :users do
    member do
      get :draft
      get :collection
      get :follower
      get :comment
    end
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :feeds, only: [:index]
  resources :invitations, only: [:create, :destroy] do
    member do
      post :accept
      post :decline
    end
  end

  resources :friendships, only: [:destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :auth
  validates_presence_of :state
  mount_uploader :image, ImageUploader
  paginates_per 20
  belongs_to :user
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories, source: :category, dependent: :destroy
  has_many :comments
  has_many :collections
  has_many :collection_users, through: :collections, source: :user, dependent: :destroy
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, message: "分類名字不能為空"
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories
end

app/models/collection.rb
class Collection < ApplicationRecord
  validates :user_id, uniqueness: { scope: :article_id }
  belongs_to :user
  belongs_to :article
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :article, counter_cache: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :user_id, uniqueness: { scope: :friend_id }
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  validates :inviter_id, uniqueness: { scope: :invitee_id }
  before_save :create_friendships
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"

  def create_friendships
    if self.state == 'accept'
      Friendship.create!(user: self.inviter, friend: self.invitee)
      Friendship.create!(user: self.invitee, friend: self.inviter)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commentted_articles, through: :comments, source: :article
  has_many :collections, dependent: :destroy
  has_many :collection_articles, through: :collections, source: :article

  has_many :invitations, -> {where(state: 'pending')}, foreign_key: :inviter_id, dependent: :destroy
  has_many :invitees, through: :invitations

  has_many :reverse_invitations, -> {where(state: 'pending')}, foreign_key: :invitee_id, class_name: "Invitation", dependent: :destroy
  has_many :inviters, through: :reverse_invitations

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  before_create :generate_authentication_token

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

  def is_friend_of?(user)
    self.friends.include?(user)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])
      # sign_in 是 Devise 的方法
      sign_in(user, store: false) if user
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @user_count = User.count
    @post_count = Article.count
    @comment_count = Comment.count
    @category_count = Category.count
    @chatter_users = User.order(comments_count: :desc).limit(10)
    @most_popular_post = Article.order(comments_count: :desc).limit(10)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def last_replied_at(article)
    if article.last_replied_at
      article.last_replied_at.strftime("%m/%d/%Y")
    end
  end

  def user_collected?(article)
    # binding.pry
    current_user.collection_articles.include?(article)
  end

  def author?(article)
    article.user == current_user
  end

  def article_can_show?(article)
    if author?(article) || article.auth == 'all'
      true
    elsif article.auth == 'self'
      false
    else
      is_friend?(article.user)
    end

  end

  def transcript_tag(tag)
    case tag
    when nil then '文章編號'
    when 'last_replied_at' then '最後回覆時間'
    when 'comments_count' then '回覆數'
    when 'views_count' then '觀看數'
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_author?(comment)
    comment.user == current_user
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def is_friend?(user)
    current_user.friends.include?(user) if current_user
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
  def is_invited?(user)
    current_user.invitees.include?(user) 
  end

  def is_invited_by?(user)
    user.invitees.include?(current_user) 
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, class_value = '')
    image_tag(gravatar_url(user), alt: user.email, class: class_value)
  end

  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end

  def title(user)
    user == current_user ? "我" : user.name
  end

  def admin?
    current_user.role == 'admin'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Dojo Forum", root_path, class: "navbar-brand" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "全站訊息", feeds_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "全部文章", articles_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "新增文章", new_article_path, class: 'nav-link' %>
          </li>
        </ul>
        <% if current_user %>
          <ul class="navbar-nav ml-auto">
            <% if admin? %>
              <li class="nav-item">
                <%= link_to "後台管理", admin_root_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to current_user.email, user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                帳號
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to('登出', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
                <%= link_to('修改個人資料', edit_user_path(current_user), class: "dropdown-item") %>
                <%= link_to('修改密碼', edit_user_registration_path, class: "dropdown-item") %>
              </div>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to('登入', new_user_session_path, class: "nav-link") %>
            </li> 
          </ul>
        <% end %>
      </div>
    </nav>
    <% if current_user %>
        <p class="pull-right">你的 API Token：<code><%= current_user.authentication_token  %></code></p>
      <% end %>
    <% if flash[:alert] %>
      <div class="container">
        <div class="row">
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= alert %>
          </div>
        </div>
     </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="container">
        <div class="row">
          <div class="alert alert-success alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= notice %>
          </div>
        </div>
     </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <!-- <%= render 'shared/footer' %> -->
  </body>
</html>

app/views/shared/_admin_delete_button.html.erb
<% if admin? && !author?(article) %>
  <%= link_to article_path(article), method: :delete do %>
    <%= fa_icon "trash", class: "fa-2x pull-left"%>
  <% end %>
<% end %>

app/views/shared/_article_table.html.erb
<table class="table">
  <thead>
    <th scope="col">回覆數</th>
    <th scope="col">標題</th>
    <th scope="col">內容</th> 
    <th scope="col">最後回覆時間</th>
    <th scope="col">觀看次數</th>
    <th scope="col">作者</th>
  </thead>
  <tbody>
    <!-- 在前端擋住不能show的文章 -->
    <% articles.each do |article| %>
      <% if article_can_show?(article) %>
        <tr>
          <td><%= article.comments_count %></td>
          <td>
            <%= link_to article.title, article %>
          </td>
          <td><%= truncate article.content %></td>
          <td><%= last_replied_at(article) %></td>
          <td><i class="fa fa-eye fa-lg"> </i> <%= article.views_count %></td>
          <td><%= link_to article.user.name, article.user %></td>
        </tr> 
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate articles %>

app/views/shared/_articles_list.html.erb
<table class="table">
  <tbody>
    <% articles.each do |article| %>
      <tr>
        <td>
          <%= link_to article.title, article %>
        </td>
        <td><%= article.state %></td>
        <td><%= article.created_at %></td>
        <td>
          <%= render "shared/collection", article: article %>
        </td>
        <td>
          <%= render "shared/author_panel", article: article %>
        </td>
      </tr> 
    <% end %>
  </tbody>
</table>

app/views/shared/_author_panel.html.erb
<% if author?(article) %>
  <%= link_to edit_article_path(article) do %>
    <%= fa_icon "pencil", class: "fa-2x" %>
  <% end %>
  <%= link_to article_path(article), method: :delete do %>
    <%= fa_icon "trash", class: "fa-2x"%>
  <% end %>
<% end %>

app/views/shared/_category_order_menu.html.erb
<div class="dropdown margin-top-bottom">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    排序方式
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to "文章編號", category_path(category), class: 'dropdown-item' %>
    <%= link_to "最後回覆時間", category_path(category, tag: 'last_replied_at'), class: 'dropdown-item' %>
    <%= link_to "回覆數", category_path(category, tag: 'comments_count'), class: 'dropdown-item' %>
    <%= link_to "觀看數", category_path(category, tag: 'views_count'), class: 'dropdown-item' %>
  </div>
  <%= render 'shared/order_text' %>
</div>

app/views/shared/_collection.html.erb
<% unless author?(article) %>
  <div id="collect-<%= article.id %>">
    <% if user_collected?(article) %>
      <%= link_to "放棄收藏", uncollect_article_path(article), method: :post, remote: true %>
    <% else %>
      <%= link_to "收藏此文章", collect_article_path(article), method: :post, remote: true %>
    <% end %>
  </div>
<% end %>

app/views/shared/_comment_form.html.erb
<%= simple_form_for comment, remote: true do |f| %>
  <%= f.input :content, label: false %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/shared/_comment_panel.html.erb
<% if comment_author?(comment) %>
  <%= link_to edit_comment_path(comment), remote: true do %>
    <%= fa_icon "pencil", class: "fa-2x pull-left" %>
  <% end %>
  <%= link_to comment_path(comment), remote: true, method: :delete do %>
    <%= fa_icon "trash", class: "fa-2x"%>
  <% end %>
<% end %>

app/views/shared/_comment_table.html.erb
<div class="col-md-3">
  <%= link_to comment.user do %>
    <%= gravatar_for(comment.user, "comment-user-avartar") %>
    <%= comment.user.name %>
  <% end %>
</div>
<div class="col-md-9">
  <div class="row">
    <div class="col-md-10" id="content-<%= comment.id %>"><%= comment.content %></div>
    <div class="col-md-2">
      <%= render "shared/comment_panel", comment: comment %>
    </div>
  </div>
</div>

app/views/shared/_friend_button.html.erb
<% unless is_friend?(user) %>
  <% unless is_invited_by?(user) %>
    <% if is_invited?(user) %>
      <%= link_to "收回交友邀請", invitation_path(user), method: :delete, class: "btn btn-danger", remote: true %>
    <% else %>
      <%= link_to "發出交友邀請", invitations_path(user_id: user.id), method: :post, class: 'btn btn-primary', remote: true %>
    <% end %>
  <% else %>
    <%= link_to '同意邀請', accept_invitation_path(user), method: :post, class: 'btn btn-primary padding-bottom-avatar' %>
    <%= link_to '拒絕邀請', decline_invitation_path(user), method: :post, class: 'btn btn-danger padding-bottom-avatar' %>
  <% end %>
<% else %> 
  <%= link_to '解除好友', friendship_path(user), method: :delete, class: 'btn btn-danger padding-bottom-avatar' %>
<% end %>

app/views/shared/_order_menu.html.erb
<div class="dropdown margin-top-bottom">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    排序方式
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to "文章編號", articles_path, class: 'dropdown-item' %>
    <%= link_to "最後回覆時間", articles_path(tag: 'last_replied_at'), class: 'dropdown-item' %>
    <%= link_to "回覆數", articles_path(tag: 'comments_count'), class: 'dropdown-item' %>
    <%= link_to "觀看數", articles_path(tag: 'views_count'), class: 'dropdown-item' %>
  </div>
  <%= render 'shared/order_text' %>
</div>

app/views/shared/_order_text.html.erb
<div class="input text-center"><%= transcript_tag @order_tag %></div>

app/views/shared/_sorting_menu.html.erb
<div class="dropdown margin-top-bottom">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    選擇分類
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <li class="nav-item">
      <%= link_to "全部", articles_path, class: 'dropdown-item' %>
    </li>
    <% Category.all.each do |category| %>
      <li class="nav-item">
        <%= link_to "#{category.name}", category_path(category), class: 'dropdown-item' %>
      </li>
    <% end %>
  </div>
  <div class="input text-center"><%= @category_tag %></div>
</div>

app/views/shared/_user_profile.html.erb
<div class="row user-profile">
    <div class="col-md-4 text-center">
      <ul>
        <li>
          <%= link_to user do %>
            <%= gravatar_for(user, "user-avartar") %>
            <div><%= user.name %></div>
          <% end %>
        </li>
        <li>
          <% if user == current_user %>
            <%= link_to "編輯個人資料", edit_user_path(user), class: "btn btn-primary" %>
          <% else %>
            <div id="user-<%= user.id %>">
              <%= render "shared/friend_button", user: user %>
            </div>
          <% end %>
        </li>
      </ul>   
    </div>
    <div class="col-md-8">
      <%= user.description %>
    </div>
</div>